#!/usr/bin/env bash
# Regenerate `v-d-rt.txt` — the V-D-RT acceptance fixture (plan section 4;
# SPEC Acceptance 1(c)).
#
# WHY A GENERATED FIXTURE RATHER THAN mk-IN-THE-TEST. `mk encode --keys` must
# actually run for V-D-RT to mean anything, and `mk` is a SIBLING repo's
# binary that CI for this repo does not build (`cargo test --workspace
# --all-targets`, .github/workflows/ci.yml). A test that shelled out to mk
# would either red CI or skip — and a skipped gate prints ok. So mk runs HERE,
# its output is committed, and the test asserts byte-for-byte that what
# decompose emits today is what mk consumed. Drift in the emission fails the
# test; drift in mk fails a re-run of this script. Same pattern, same reasons,
# as ../seating/generate.sh.
#
# Two binaries, both resolved BY PATH on purpose (a bare `md`/`mk` on $PATH may
# be a stale install, or something else entirely):
#
#   md  — this repo:            cargo build -p md-cli  ->  target/debug/md
#   mk  — sibling mnemonic-key: cargo build -p mk-cli  ->  target/debug/mk
#
# Usage, from anywhere:
#   MK=/scratch/code/shibboleth/mnemonic-key/target/debug/mk \
#     crates/md-cli/tests/fixtures/decompose/generate.sh
#
# DETERMINISM: every command below is a pure function of its input.
# `mk encode` derives its chunk-set id from the payload (mk-codec
# `derive_chunk_set_id`) rather than drawing one, and `md encode` is a pure
# function of template + keys. A re-run produces a byte-identical file, so
# `git diff` after running this is the check that the path has not rotted.
#
# THE ARTIFACTS ARE PRODUCED BY `md decompose --emit commands` ITSELF. This
# script extracts the two mint routes decompose prints and `eval`s them
# verbatim, so the fixture is evidence that the emitted commands RUN and that
# what they mint round-trips — not that some hand-written approximation does.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../../../../.." && pwd)"
MD="${MD:-$ROOT/target/debug/md}"
MK="${MK:-/scratch/code/shibboleth/mnemonic-key/target/debug/mk}"
DATE="2026-08-30"

for b in "$MD" "$MK"; do
  [ -x "$b" ] || { echo "missing binary: $b (see the header of this script)" >&2; exit 1; }
done

KEYS="$HERE/../pathological/keys.txt"
OUT="$HERE/v-d-rt.txt"

# ── the PINNED depth-consistent fixture: records 1-3 of keys.txt (SPEC
#    Acceptance 1(c), r2 M5). Each is a depth-4 xpub whose origin path has four
#    components ending in the xpub's own child number, so mk accepts them.
mapfile -t K < <(grep -v '^#' "$KEYS" | grep -v '^[[:space:]]*$' | head -3)
[ "${#K[@]}" -eq 3 ] || { echo "expected 3 key records, got ${#K[@]}" >&2; exit 1; }
DESC="wsh(sortedmulti(2,${K[0]}/<0;1>/*,${K[1]}/<0;1>/*,${K[2]}/<0;1>/*))"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/bin"
ln -sf "$MD" "$WORK/bin/md"
ln -sf "$MK" "$WORK/bin/mk"
export PATH="$WORK/bin:$PATH"

TEMPLATE="$("$MD" decompose "$DESC" --emit template)"
"$MD" decompose "$DESC" --emit keys        > "$WORK/emitted-keys.txt"
"$MD" decompose "$DESC" --emit descriptor  > "$WORK/canonical.txt"
"$MD" decompose "$DESC" --emit commands    > "$WORK/commands.sh"

# Route 1 (the KEYED card) is the block from the first `md encode` line to the
# next blank line; route 2 (the SPLIT set) is everything after it, comments and
# all. Both are eval'd exactly as printed.
awk '/^md encode /{f=1} f&&NF==0{exit} f' "$WORK/commands.sh" > "$WORK/route1.sh"
awk 'BEGIN{n=0} /^md encode /{n++} n==2{print}' "$WORK/commands.sh" > "$WORK/route2.sh"

# Exit codes are captured rather than assumed: the header below STATES that md
# and mk accepted the emissions, and a claim in a fixture header has to be a
# measurement or it is decoration.
set +e
( cd "$WORK" && bash route1.sh > keyed.md1 2> route1.err ); R1=$?
( cd "$WORK" && bash route2.sh > cards.mk1 2> route2.err ); R2=$?
set -e
[ "$R1" -eq 0 ] || { echo "route 1 failed ($R1):"; cat "$WORK/route1.err"; exit 1; }
[ "$R2" -eq 0 ] || { echo "route 2 failed ($R2):"; cat "$WORK/route2.err"; exit 1; }

emit() {
  printf '%s\n' "$1"
}

{
  echo "# V-D-RT — the acceptance-grade decompose round trip (plan section 4;"
  echo "# SPEC Acceptance 1(c): \"md decompose of the PINNED depth-consistent fixture"
  echo "# emits a template + key file that md encode --key + mk encode --keys accept"
  echo "# and that re-compose ROUND-TRIP-EQUAL\")."
  echo "#"
  echo "# GENERATED by crates/md-cli/tests/fixtures/decompose/generate.sh on $DATE."
  echo "# Key material: records 1-3 of ../pathological/keys.txt — the pinned"
  echo "# depth-consistent fixture (r2 M5). Sections are introduced by '# @@ <name>';"
  echo "# every other '#' line and every blank line is provenance only."
  echo "#"
  echo "# The two mint routes below were NOT hand-written: they are the output of"
  echo "#   md decompose <input-descriptor> --emit commands"
  echo "# eval'd verbatim in a scratch directory with md and mk on PATH."
  echo "# Measured exit codes: route 1 (md encode --key) = $R1; route 2 (md encode"
  echo "# --out, then mk encode --keys --from-md1-set) = $R2."
  echo "#"
  echo "# Route 1 (keyed card):"
  sed 's/^/#   /' "$WORK/route1.sh"
  echo "# Route 2 (split set):"
  sed 's/^/#   /' "$WORK/route2.sh"
  echo ""
  echo "# @@ input-descriptor"
  emit "$DESC"
  echo "# @@ canonical-descriptor"
  cat "$WORK/canonical.txt"
  echo "# @@ template"
  emit "$TEMPLATE"
  echo "# @@ keys"
  cat "$WORK/emitted-keys.txt"
  echo "# @@ keyed-card"
  grep '^md1' "$WORK/keyed.md1"
  echo "# @@ policy-card"
  grep '^md1' "$WORK/policy.md1"
  echo "# @@ mk1-cards"
  grep '^mk1' "$WORK/cards.mk1"
} > "$OUT"

echo "wrote $OUT"
