#!/usr/bin/env bash
# Regenerate every SYNTHETIC seating fixture in this directory.
#
# The real ones live in `../pathological/` and are COPIES, not generations —
# see their own provenance headers.
#
# Two binaries are needed, and both are resolved BY PATH on purpose (a bare
# `md`/`mk` on $PATH may be a stale install, or something else entirely):
#
#   md  — this repo:            cargo build -p md-cli  ->  target/debug/md
#   mk  — sibling mnemonic-key: cargo build -p mk-cli  ->  target/debug/mk
#
# Usage, from anywhere:
#   MK=/scratch/code/shibboleth/mnemonic-key/target/debug/mk \
#     crates/md-cli/tests/fixtures/seating/generate.sh
#
# Every emitted file repeats the exact commands that produced it, so a reader
# can regenerate ONE fixture without running the whole script.
#
# DETERMINISM: every command below is deterministic. `mk encode` derives its
# chunk-set id from the payload (mk-codec `derive_chunk_set_id`) rather than
# drawing one, and `md encode` is a pure function of the template, so a
# re-run produces byte-identical files. `git diff` after a re-run is the
# check that the generator has not rotted.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../../../../.." && pwd)"
MD="${MD:-$ROOT/target/debug/md}"
MK="${MK:-/scratch/code/shibboleth/mnemonic-key/target/debug/mk}"
DATE="2026-08-30"

for b in "$MD" "$MK"; do
  [ -x "$b" ] || { echo "missing binary: $b (see the header of this script)" >&2; exit 1; }
done

KEYS="$HERE/../pathological/keys.txt"
BACKUP="$HERE/../pathological/backup-strings.txt"

# ── key material ────────────────────────────────────────────────────────────
mapfile -t KEYLINE < <(grep -v '^#' "$KEYS" | grep -v '^[[:space:]]*$')
xpub_of() { printf '%s\n' "${KEYLINE[$1]}" | sed 's/^\[[^]]*\]//'; }
fp_of()   { printf '%s\n' "${KEYLINE[$1]}" | sed 's/^\[\([0-9a-f]*\)\/.*/\1/'; }
path_of() { printf '%s\n' "${KEYLINE[$1]}" | sed 's/^\[[0-9a-f]*\/\([^]]*\)\].*/\1/'; }

mint() { # mint <xpub> <origin-path> <stub> [extra mk encode flags...]
  local xpub="$1" path="$2" stub="$3"; shift 3
  "$MK" encode --xpub "$xpub" --origin-path "$path" --policy-id-stub "$stub" \
        --group-size 0 "$@" 2>/dev/null
}

# A depth-5 child of pathological key <i>, at relative m/<c>.
#
# `mk derive` takes a CARD, so mint a throwaway one first. `mk encode` checks
# the xpub's depth and child number against the origin path's length and LAST
# component — and nothing else (measured 2026-08-30: "xpub origin-path
# mismatch: xpub depth 5 / child 7 vs origin_path depth 5 / last Normal{0}") —
# so every child at m/0 may declare the SAME 5-component path regardless of
# which parent it came from. That is what makes N distinct fp-free cards at
# ONE declared origin constructible from 11 keys.
child_of() { # child_of <parent 0..10> <child index>
  local i="$1" c="$2" tmp
  tmp=$(mint "$(xpub_of "$i")" "m/$(path_of "$i")" 00000000 \
              --origin-fingerprint "$(fp_of "$i")")
  # shellcheck disable=SC2086
  "$MK" derive --path "m/$c" $tmp 2>/dev/null | awk '/^child_xpub/{print $2}'
}

header() { # header <file> <row> <description>
  {
    echo "# $2 — $3"
    echo "# GENERATED by crates/md-cli/tests/fixtures/seating/generate.sh on $DATE."
    echo "# Key material: crates/md-cli/tests/fixtures/pathological/keys.txt (KEY n = its"
    echo "# n-th record, 1-based). md1 lines are the keyless policy card; mk1 lines are"
    echo "# the key cards. '#' and blank lines are provenance only."
  } > "$1"
}

# Shared 5-component paths for the fingerprint-free families. Depth-5 children
# at m/0 (component A) and m/1 (component B) — see child_of.
PA="48'/0'/0'/2'/0"
PB="48'/0'/1'/2'/1"

# ── V-COLLIDE ───────────────────────────────────────────────────────────────
f="$HERE/v-collide.txt"
header "$f" V-COLLIDE "two DIFFERENT cards pinned to one chunk-set id (0x12345)"
{
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35 --chunk-set-id 0x12345"
  echo "#   mk encode --xpub <KEY 2> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/1'/2' --policy-id-stub 5b48af35 --chunk-set-id 0x12345"
  echo "# Card A's chunks come FIRST so a test may take them alone and prove each card"
  echo "# decodes by itself — the refusal is the MERGED group, not a broken card."
  mint "$(xpub_of 0)" "m/$(path_of 0)" 5b48af35 --origin-fingerprint "$(fp_of 0)" --chunk-set-id 0x12345
  mint "$(xpub_of 1)" "m/$(path_of 1)" 5b48af35 --origin-fingerprint "$(fp_of 1)" --chunk-set-id 0x12345
} >> "$f"
echo "wrote: $f"

# ── V-IMPOSS ────────────────────────────────────────────────────────────────
# Two cards claiming the identical (fingerprint, path) with DIFFERENT xpubs.
# KEY 2's xpub is minted at KEY 1's origin: both are depth 4 and both paths end
# in 2', which is all `mk encode` checks, so the declaration is a lie the format
# itself cannot catch — exactly the case A2 has to.
f="$HERE/v-imposs.txt"
header "$f" V-IMPOSS "two cards, identical [73c5da0a/48'/0'/0'/2'], different xpubs"
{
  echo "#   md encode \"wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))\" \\"
  echo "#     --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a"
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  echo "#   mk encode --xpub <KEY 2> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35   <-- the lie"
  "$MD" encode "wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))" \
        --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint 73c5da0a
  mint "$(xpub_of 1)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint 73c5da0a
} >> "$f"
echo "wrote: $f"

# ── V-DOOR ──────────────────────────────────────────────────────────────────
# A policy whose @0 and @1 declare the IDENTICAL fingerprint-bearing origin.
# Its only possible fill binds one xpub to both slots.
f="$HERE/v-door.txt"
header "$f" V-DOOR "policy declaring two identical fingerprint-bearing slots"
{
  echo "#   md encode \"wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))\" \\"
  echo "#     --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a"
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  "$MD" encode "wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))" \
        --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint 73c5da0a
} >> "$f"
echo "wrote: $f"

# ── V-FPFREE-CARD ───────────────────────────────────────────────────────────
# @0 declares a fingerprint; the only card at @0's path is privacy-preserving,
# so it cannot meet that requirement blind and @0 is unfillable.
f="$HERE/v-fpfree-card.txt"
header "$f" V-FPFREE-CARD "fingerprint-free CARD against a fingerprint-BEARING declaration"
{
  echo "#   md encode \"wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))\" \\"
  echo "#     --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a"
  echo "#   mk encode --xpub <KEY 1> --privacy-preserving \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  echo "#   mk encode --xpub <KEY 2> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/1'/2' --policy-id-stub 5b48af35"
  "$MD" encode "wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))" \
        --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --privacy-preserving
  mint "$(xpub_of 1)" "m/48'/0'/1'/2'" 5b48af35 --origin-fingerprint 73c5da0a
} >> "$f"
echo "wrote: $f"

# ── V-R5M1 — FROZEN BY DESIGN, NOT GENERATED ────────────────────────────────
#
# r5-M1's construction: @0 and @1 each appear in TWO group instances at the
# same use-site path, which is exactly the repetition BIP 388 forbids. It
# shipped as a measured over-strictness note and became a REFUSE row under the
# 2026-08-30 key-reuse ruling.
#
# WHY THIS BLOCK NO LONGER MINTS. Since the mdcli-mini cycle's N1 taxonomy
# (`design/SPEC_mdcli_mini.md` R-N1a, phase P2) `md encode` REFUSES that
# template, so the command below would exit 1. Under this script's `set -e`
# that is not merely a missing fixture: the redirection `> "$f"` in `header`
# runs FIRST, so v-r5m1.txt would be truncated to a header and the script would
# then die -- leaving the 17 fixtures written after this point unregenerated,
# and one fixture silently emptied.
#
# The file is therefore FROZEN: it was minted from the b8a64938 code surface
# and no shipped binary can mint it again. Measured 2026-08-30 at P2 time: a
# full run of this generator against that baseline binary reproduced
# v-r5m1.txt (and every other fixture) byte-identically, so the committed file
# IS this block's final output. To regenerate it you must check out b8a64938.
#
# What remains here is an EXISTENCE ASSERT, deliberately stronger than `-e`:
# an empty or half-written file is the exact failure this replaces, so the
# check requires the fixture still to carry both halves it is used for.
f="$HERE/v-r5m1.txt"
grep -q '^md1' "$f" 2>/dev/null && grep -q '^mk1' "$f" 2>/dev/null || {
  echo "frozen fixture missing or truncated: $f (see the note above; it cannot be regenerated by a current binary)" >&2
  exit 1
}
echo "kept (frozen, not regenerable): $f"

# ── V-BOUND-SEAT ────────────────────────────────────────────────────────────
# The SEAT side of the key-reuse boundary: fingerprint-free declarations at ONE
# path, two DIFFERENT masters. Pairwise-distinct keys, not reuse — and the
# sortedmulti group makes both assignments the same wallet, so it must SEAT.
f="$HERE/v-bound-seat.txt"
header "$f" V-BOUND-SEAT "fingerprint-free same-path declarations, two different masters"
{
  echo "#   md encode \"wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))\""
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  echo "#   mk encode --xpub <KEY 5> --origin-fingerprint b8688df1 \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  "$MD" encode "wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))" \
        --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of 0)"
  mint "$(xpub_of 4)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of 4)"
} >> "$f"
echo "wrote: $f"

# ── V-BOUND-REF ─────────────────────────────────────────────────────────────
# The REFUSE side, sitting adjacent so the boundary is pinned from BOTH
# directions: the SAME xpub offered as two cards (distinguished by their
# stubs, so they are two cards and not one duplicate the pipeline collapses).
f="$HERE/v-bound-ref.txt"
header "$f" V-BOUND-REF "the same xpub offered as two cards, for two slots"
{
  echo "#   md encode \"wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))\""
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 00000000"
  "$MD" encode "wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))" \
        --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of 0)"
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 00000000 --origin-fingerprint "$(fp_of 0)"
} >> "$f"
echo "wrote: $f"

# ── V-BOUND-REF-PATHS ───────────────────────────────────────────────────────
# V-BOUND-REF's SIBLING, and the point of it: the same xpub offered as two
# cards that declare DIFFERENT origin paths. `check_no_repeated_xpub` compares
# KEY MATERIAL and nothing else, so it refuses this pair too -- and it is the
# check that answers, because the two paths differ and therefore neither
# `check_no_identical_fp_bearing_declarations` (identical declared origins) nor
# `check_no_impossible_card_pair` (one origin, two xpubs) fires.
#
# The declarations are honest about the SHAPE and dishonest about one card, the
# way V-IMPOSS is: KEY 1 is minted a second time at 48'/0'/1'/2', which
# `mk encode` accepts because it checks only depth and the last component.
# What the fixture pins is the ENGINE's answer, not the card's provenance.
#
# Measured shipped behaviour, 2026-08-31 -- unpinned until plan P3 step 3.
f="$HERE/v-bound-ref-paths.txt"
header "$f" V-BOUND-REF-PATHS "the same xpub declared at two DIFFERENT paths"
{
  echo "#   md encode \"wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))\""
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/1'/2' --policy-id-stub 5b48af35   <-- KEY 1 again"
  "$MD" encode "wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))" \
        --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of 0)"
  mint "$(xpub_of 0)" "m/48'/0'/1'/2'" 5b48af35 --origin-fingerprint "$(fp_of 0)"
} >> "$f"
echo "wrote: $f"

# ── V-USP (also the V-AMB / V-SEAT-* fixture) ───────────────────────────────
# r5's counterexample. One sortedmulti, two fingerprint-free slots at ONE
# origin — but DIFFERENT use-site paths, so swapping the cards changes which
# xpub derives at which chain. Sorting cannot recover what derivation already
# changed: two wallets, so it must REFUSE.
f="$HERE/v-usp.txt"
header "$f" V-USP "use-site-path swap: same origin, <0;1> vs <2;3>"
{
  echo "#   md encode \"wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<2;3>/*))\""
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  echo "#   mk encode --xpub <KEY 5> --origin-fingerprint b8688df1 \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  "$MD" encode "wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<2;3>/*))" \
        --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of 0)"
  mint "$(xpub_of 4)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of 4)"
} >> "$f"
echo "wrote: $f"

# ── V-MIX ───────────────────────────────────────────────────────────────────
# r6-M2's shape: MIXED declarations with a UNIQUE matching, so it must SEAT.
# @0 declares fingerprint 73c5da0a; @1 declares the same path and NO
# fingerprint. Card A (73c5da0a) satisfies both slots, card B (b8688df1)
# satisfies only @1 — one perfect matching.
f="$HERE/v-mix.txt"
header "$f" V-MIX "mixed declarations (one fp-bearing, one fp-free), unique matching"
{
  echo "#   md encode \"wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))\" \\"
  echo "#     --fingerprint @0=73c5da0a"
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  echo "#   mk encode --xpub <KEY 5> --origin-fingerprint b8688df1 \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  "$MD" encode "wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))" \
        --fingerprint @0=73c5da0a --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of 0)"
  mint "$(xpub_of 4)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of 4)"
} >> "$f"
echo "wrote: $f"

# ── the fingerprint-free depth-5 families ───────────────────────────────────
# Four, five and twelve distinct cards at ONE declared origin. See child_of.
mint_child() { # mint_child <parent 0..10> <child index> <declared path>
  mint "$(child_of "$1" "$2")" "m/$3" 5b48af35 --privacy-preserving
}

# ── V-R2-ORD ────────────────────────────────────────────────────────────────
# r2(a): two `multi` GROUPS, four indistinguishable cards. r2 measured three
# supply orders producing three different wallets; under THIS procedure the
# verdict must be REFUSE, and identically in every order (r1 I1 -- the
# verdict is order-invariant, not merely the bytes).
f="$HERE/v-r2-ord.txt"
header "$f" V-R2-ORD "r2's three-orders counterexample: two multi groups, four fp-free cards"
{
  echo "#   md encode \"wsh(or_i(multi(2,@0/$PA/<0;1>/*,@1/$PA/<0;1>/*),multi(2,@2/$PA/<0;1>/*,@3/$PA/<0;1>/*)))\""
  echo "#   for parent in 1 2 3 4: mk encode --privacy-preserving \\"
  echo "#     --xpub \$(mk derive --path m/0 <parent's card>) \\"
  echo "#     --origin-path m/$PA --policy-id-stub 5b48af35"
  "$MD" encode "wsh(or_i(multi(2,@0/$PA/<0;1>/*,@1/$PA/<0;1>/*),multi(2,@2/$PA/<0;1>/*,@3/$PA/<0;1>/*)))" \
        --group-size 0 2>/dev/null
  for p in 0 1 2 3; do mint_child "$p" 0 "$PA"; done
} >> "$f"
echo "wrote: $f"

# ── V-R4-IK ─────────────────────────────────────────────────────────────────
# r2(b) / r4's internal-key hazard in a REUSE-FREE five-distinct-key form: the
# taproot internal key is a member of no group, so a card landing on @0 holds
# the unilateral keyspend path. Must REFUSE.
f="$HERE/v-r4-ik.txt"
header "$f" V-R4-IK "taproot internal key vs leaf repartition, five fp-free cards"
{
  echo "#   md encode \"tr(@0/$PA/<0;1>/*,{sortedmulti_a(2,@1/$PA/<0;1>/*,@2/$PA/<0;1>/*),sortedmulti_a(2,@3/$PA/<0;1>/*,@4/$PA/<0;1>/*)})\""
  echo "#   for parent in 1..5: mk encode --privacy-preserving \\"
  echo "#     --xpub \$(mk derive --path m/0 <parent's card>) \\"
  echo "#     --origin-path m/$PA --policy-id-stub 5b48af35"
  "$MD" encode "tr(@0/$PA/<0;1>/*,{sortedmulti_a(2,@1/$PA/<0;1>/*,@2/$PA/<0;1>/*),sortedmulti_a(2,@3/$PA/<0;1>/*,@4/$PA/<0;1>/*)})" \
        --group-size 0 2>/dev/null
  for p in 0 1 2 3 4; do mint_child "$p" 0 "$PA"; done
} >> "$f"
echo "wrote: $f"

# ── V-GRP ───────────────────────────────────────────────────────────────────
# r3's two-group repartition: BOTH endpoints sit inside sorted groups, so a
# position-based rule permits it -- but the groups have different arities and
# a card landing in the 1-of-2 leaf holds unilateral spending authority the
# operator meant to be shared. Must REFUSE.
f="$HERE/v-grp.txt"
header "$f" V-GRP "two sortedmulti_a groups of DIFFERENT arity (2-of-2 and 1-of-2)"
{
  echo "#   md encode \"tr(@0/$PA/<0;1>/*,{sortedmulti_a(2,@1/$PA/<0;1>/*,@2/$PA/<0;1>/*),sortedmulti_a(1,@3/$PA/<0;1>/*,@4/$PA/<0;1>/*)})\""
  echo "#   for parent in 1..5: mk encode --privacy-preserving \\"
  echo "#     --xpub \$(mk derive --path m/0 <parent's card>) \\"
  echo "#     --origin-path m/$PA --policy-id-stub 5b48af35"
  "$MD" encode "tr(@0/$PA/<0;1>/*,{sortedmulti_a(2,@1/$PA/<0;1>/*,@2/$PA/<0;1>/*),sortedmulti_a(1,@3/$PA/<0;1>/*,@4/$PA/<0;1>/*)})" \
        --group-size 0 2>/dev/null
  for p in 0 1 2 3 4; do mint_child "$p" 0 "$PA"; done
} >> "$f"
echo "wrote: $f"

# ── V-CAP ───────────────────────────────────────────────────────────────────
# TWO INDEPENDENT six-card components: 6! x 6! = 518,400 perfect matchings,
# with no component over 6. This is r6-I2's construction -- the shape a
# per-class k! bound neither bounds nor tracks -- so it pins that the cap is
# on TOTAL matchings enumerated.
f="$HERE/v-cap.txt"
header "$f" V-CAP "two independent 6-card components (518,400 matchings)"
{
  echo "#   md encode \"wsh(or_i(multi(3,@0..@5 at $PA),multi(3,@6..@11 at $PB)))\""
  echo "#   for parent in 1..6: mk encode --privacy-preserving \\"
  echo "#     --xpub \$(mk derive --path m/0 <parent's card>) --origin-path m/$PA ..."
  echo "#   for parent in 1..6: mk encode --privacy-preserving \\"
  echo "#     --xpub \$(mk derive --path m/1 <parent's card>) --origin-path m/$PB ..."
  A=""; for i in 0 1 2 3 4 5; do A="$A,@$i/$PA/<0;1>/*"; done
  B=""; for i in 6 7 8 9 10 11; do B="$B,@$i/$PB/<0;1>/*"; done
  "$MD" encode "wsh(or_i(multi(3${A}),multi(3${B})))" --group-size 0 2>/dev/null
  for p in 0 1 2 3 4 5; do mint_child "$p" 0 "$PA"; done
  for p in 0 1 2 3 4 5; do mint_child "$p" 1 "$PB"; done
} >> "$f"
echo "wrote: $f"

# ── V-LEFTOVER ──────────────────────────────────────────────────────────────
# ONE extra card at an origin the pathological policy never declares.
#
# Its xpub is a depth-5 CHILD, not one of the eleven: an extra card carrying a
# pathological xpub trips A3's pairwise-distinct check FIRST (measured
# 2026-08-30 -- the earlier draft of this fixture reused KEY 5 and the engine
# refused with "carry the SAME extended public key", never reaching A4), so the
# row would have pinned the wrong refusal.
f="$HERE/v-leftover.txt"
header "$f" V-LEFTOVER "one extra foreign card, at an origin the policy never declares"
{
  echo "#   mk encode --privacy-preserving \\"
  echo "#     --xpub \$(mk derive --path m/0 <KEY 5's card>) \\"
  echo "#     --origin-path m/48'/0'/9'/2'/0 --policy-id-stub 5b48af35"
  echo "# Append to tests/fixtures/pathological/backup-strings.txt's mk1 half."
  mint "$(child_of 4 0)" "m/48'/0'/9'/2'/0" 5b48af35 --privacy-preserving
} >> "$f"
echo "wrote: $f"

# ── V-UNFILLED ──────────────────────────────────────────────────────────────
# The pathological policy with TEN of its eleven cards: the card declaring
# 48'/0'/3'/2' is dropped, so @3 is unfillable and nothing is left over.
#
# The dropped group is found by DECODING each card, not by slicing lines --
# chunk membership is a property of the string-layer header, and a line-count
# guess would silently drop a different card.
f="$HERE/v-unfilled.txt"
header "$f" V-UNFILLED "the pathological set minus the card for 48'/0'/3'/2'"
{
  echo "#   grep '^md1' backup-strings.txt"
  echo "#   every mk1 chunk whose card does NOT decode to [73c5da0a/48'/0'/3'/2'],"
  echo "#   grouped by the leading header symbols and checked with \`mk decode\`."
  grep '^md1' "$BACKUP"
  prev=""; group=()
  emit_group() {
    if [ ${#group[@]} -gt 0 ]; then
      local d
      d=$("$MK" decode "${group[@]}" 2>/dev/null)
      # BOTH halves of the origin: two of the eleven keys sit at
      # 48'/0'/3'/2' under different masters, and matching on the path
      # alone drops them both (measured -- the first draft of this fixture
      # left TWO slots unfilled instead of one).
      if ! { grep -q "origin_fingerprint: *73c5da0a" <<<"$d" \
             && grep -q "origin_path: *48'/0'/3'/2'" <<<"$d"; }; then
        printf '%s\n' "${group[@]}"
      fi
    fi
    return 0
  }
  while read -r line; do
    key="${line:0:10}"
    if [ "$key" != "$prev" ]; then emit_group; group=(); prev="$key"; fi
    group+=("$line")
  done < <(grep '^mk1' "$BACKUP")
  emit_group
} >> "$f"
echo "wrote: $f"

# ── the B1 family ───────────────────────────────────────────────────────────
# All four share ONE policy so the three dispositions differ only in the stub
# each card was minted against, which is the variable B1 is about.
B1_TPL="wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))"
B1_FPS=(--fingerprint @0=73c5da0a --fingerprint @1=73c5da0a)

b1_keyless() { "$MD" encode "$B1_TPL" "${B1_FPS[@]}" --group-size 0 2>/dev/null; }
b1_keyed()   { # b1_keyed <fp for both slots>
  "$MD" encode "$B1_TPL" --key "@0=$(xpub_of 0)" --key "@1=$(xpub_of 1)" \
        --fingerprint "@0=$1" --fingerprint "@1=$1" --group-size 0 2>/dev/null
}
id_of() { # id_of <field> <md1 strings...>
  local field="$1"; shift
  # shellcheck disable=SC2086
  "$MD" inspect $* 2>/dev/null | awk -v f="$field:" '$1 == f {print substr($2,1,8)}'
}

B1_KEYED=$(b1_keyed 73c5da0a)
# shellcheck disable=SC2086
B1_WALLET_ID=$(id_of wallet-policy-id $B1_KEYED)
# shellcheck disable=SC2086
B1_SHAPE_ID=$(id_of wallet-descriptor-template-id $(b1_keyless))
[ ${#B1_WALLET_ID} -eq 8 ] || { echo "wallet-policy-id extraction failed" >&2; exit 1; }
[ ${#B1_SHAPE_ID} -eq 8 ]  || { echo "template-id extraction failed" >&2; exit 1; }

b1_fixture() { # b1_fixture <file> <row> <desc> <stub> <extra provenance line>
  header "$1" "$2" "$3"
  {
    echo "#   md encode \"$B1_TPL\" --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a"
    echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
    echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub $4"
    echo "#   mk encode --xpub <KEY 2> --origin-fingerprint 73c5da0a \\"
    echo "#     --origin-path m/48'/0'/1'/2' --policy-id-stub $4"
    echo "# $5"
    b1_keyless
    mint "$(xpub_of 0)" "m/48'/0'/0'/2'" "$4" --origin-fingerprint 73c5da0a
    mint "$(xpub_of 1)" "m/48'/0'/1'/2'" "$4" --origin-fingerprint 73c5da0a
  } >> "$1"
  echo "wrote: $1"
}

b1_fixture "$HERE/v-b1-wallet.txt" V-B1-WALLET \
  "cards stubbed with the COMPOSED wallet id -> wallet-confirmed" \
  "$B1_WALLET_ID" \
  "Stub $B1_WALLET_ID is the top 4 bytes of this composition's WalletPolicyId (measured with md inspect on the keyed card built from the same template + keys)."

b1_fixture "$HERE/v-b1-shape.txt" V-B1-SHAPE \
  "cards stubbed with this policy's own template id -> shape-confirmed" \
  "$B1_SHAPE_ID" \
  "Stub $B1_SHAPE_ID is the top 4 bytes of this policy's WalletDescriptorTemplateId."

b1_fixture "$HERE/v-b1-warn.txt" V-B1-WARN \
  "cards stubbed 232214e4 -- neither this shape nor this wallet" \
  232214e4 \
  "232214e4 is SPEC A1's measured value: the stub a card minted --from-md1 <the pathological KEYED card> carries. It matches neither the template id nor the composed wallet id, and all three are legitimate. The permanent row for the r3-C3 counterexample."

b1_fixture "$HERE/v-b1-cross.txt" V-B1-CROSS \
  "cards stubbed with a DIFFERENT wallet's shape id" \
  5b48af35 \
  "5b48af35 is the PATHOLOGICAL policy's template id -- a real shape id, belonging to another wallet entirely. Cross-shape: warn, never refuse."

# The keyed card for the cross-form spend-equality row, deliberately minted
# with DIFFERENT origin metadata (fingerprint b8688df1 on both slots) so the
# row exercises r3-C2's point: the two forms declare different origins and
# must still be SPEND-EQUAL.
f="$HERE/v-spendeq-keyed.txt"
header "$f" V-SPENDEQ "the same wallet as a KEYED card, with different origin metadata"
{
  echo "#   md encode \"$B1_TPL\" --key @0=<KEY 1> --key @1=<KEY 2> \\"
  echo "#     --fingerprint @0=b8688df1 --fingerprint @1=b8688df1"
  echo "# Same template, same keys, same use-site paths; DIFFERENT declared"
  echo "# fingerprints from v-b1-wallet.txt's split set. Spend-equal, not"
  echo "# round-trip-equal -- the distinction acceptance 1 exists to draw."
  b1_keyed b8688df1
} >> "$f"
echo "wrote: $f"

# ── V-CE1 ───────────────────────────────────────────────────────────────────
# A fingerprint-FREE policy, the genuine pair, and a FOREIGN card carrying the
# SAME stub at @0's path. The foreign card seats (A2's third cell -- the named
# residue) and the derived address differs. Both halves are the row.
CE1_TPL="wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))"
# shellcheck disable=SC2086
CE1_SHAPE=$(id_of wallet-descriptor-template-id $("$MD" encode "$CE1_TPL" --group-size 0 2>/dev/null))
[ ${#CE1_SHAPE} -eq 8 ] || { echo "CE1 template-id extraction failed" >&2; exit 1; }

f="$HERE/v-ce1.txt"
header "$f" V-CE1 "fingerprint-free policy + the GENUINE pair (stub $CE1_SHAPE)"
{
  echo "#   md encode \"$CE1_TPL\"        (no --fingerprint: fp-free declarations)"
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub $CE1_SHAPE"
  echo "#   mk encode --xpub <KEY 2> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/1'/2' --policy-id-stub $CE1_SHAPE"
  "$MD" encode "$CE1_TPL" --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" "$CE1_SHAPE" --origin-fingerprint "$(fp_of 0)"
  mint "$(xpub_of 1)" "m/48'/0'/1'/2'" "$CE1_SHAPE" --origin-fingerprint "$(fp_of 1)"
} >> "$f"
echo "wrote: $f"

f="$HERE/v-ce1-foreign.txt"
header "$f" V-CE1 "the FOREIGN card: another master, @0's path, the SAME stub"
{
  echo "#   mk encode --xpub <KEY 5> --origin-fingerprint b8688df1 \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub $CE1_SHAPE"
  echo "# Substitute it for v-ce1.txt's first card. Nothing in the engine can"
  echo "# tell it apart -- the policy declares no fingerprint to discriminate"
  echo "# with, and that is the policy AUTHOR's accepted risk (SPEC A2, r5 M2)."
  mint "$(xpub_of 4)" "m/48'/0'/0'/2'" "$CE1_SHAPE" --origin-fingerprint "$(fp_of 4)"
} >> "$f"
echo "wrote: $f"

# ── V-LEGACY-P2SH (whole-diff review r1 I3) ─────────────────────────────────
# `sh(sortedmulti(...))` -- CE1's own template, re-wrapped in legacy P2SH
# instead of wsh -- fingerprint-bearing so ONE card each seats unambiguously,
# no stub-matching needed. Exists so `--emit md1` has a legacy-P2SH policy it
# can seat from a split card set: F-A4's footgun advisory fires only on the
# top-level bare sh(multi)/sh(sortedmulti) shape, and no fixture in this
# directory carried it before this row.
LEGACY_P2SH_TPL="sh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))"
LEGACY_P2SH_KEYED=$("$MD" encode "$LEGACY_P2SH_TPL" --key "@0=$(xpub_of 0)" \
      --key "@1=$(xpub_of 1)" --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a \
      --group-size 0 2>/dev/null)
# shellcheck disable=SC2086
LEGACY_P2SH_WALLET_ID=$(id_of wallet-policy-id $LEGACY_P2SH_KEYED)
[ ${#LEGACY_P2SH_WALLET_ID} -eq 8 ] || { echo "V-LEGACY-P2SH wallet-policy-id extraction failed" >&2; exit 1; }

f="$HERE/v-legacy-p2sh.txt"
header "$f" V-LEGACY-P2SH "a bare sh(sortedmulti(...)) policy, seated from two fp-bearing cards (stub $LEGACY_P2SH_WALLET_ID)"
{
  echo "#   md encode \"$LEGACY_P2SH_TPL\" --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a"
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub $LEGACY_P2SH_WALLET_ID"
  echo "#   mk encode --xpub <KEY 2> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/1'/2' --policy-id-stub $LEGACY_P2SH_WALLET_ID"
  "$MD" encode "$LEGACY_P2SH_TPL" --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a \
        --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" "$LEGACY_P2SH_WALLET_ID" --origin-fingerprint 73c5da0a
  mint "$(xpub_of 1)" "m/48'/0'/1'/2'" "$LEGACY_P2SH_WALLET_ID" --origin-fingerprint 73c5da0a
} >> "$f"
echo "wrote: $f"
