#!/usr/bin/env bash
# Regenerate every SYNTHETIC seating fixture in this directory.
#
# The real ones live in `../pathological/` and are COPIES, not generations —
# see their own provenance headers.
#
# Two binaries are needed, and both are resolved BY PATH on purpose (a bare
# `md`/`mk` on $PATH may be a stale install, or something else entirely):
#
#   md  — this repo:            cargo build -p md-cli  ->  target/debug/md
#   mk  — sibling mnemonic-key: cargo build -p mk-cli  ->  target/debug/mk
#
# Usage, from anywhere:
#   MK=/scratch/code/shibboleth/mnemonic-key/target/debug/mk \
#     crates/md-cli/tests/fixtures/seating/generate.sh
#
# Every emitted file repeats the exact commands that produced it, so a reader
# can regenerate ONE fixture without running the whole script.
#
# DETERMINISM: every command below is deterministic. `mk encode` derives its
# chunk-set id from the payload (mk-codec `derive_chunk_set_id`) rather than
# drawing one, and `md encode` is a pure function of the template, so a
# re-run produces byte-identical files. `git diff` after a re-run is the
# check that the generator has not rotted.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../../../../.." && pwd)"
MD="${MD:-$ROOT/target/debug/md}"
MK="${MK:-/scratch/code/shibboleth/mnemonic-key/target/debug/mk}"
DATE="2026-08-30"

for b in "$MD" "$MK"; do
  [ -x "$b" ] || { echo "missing binary: $b (see the header of this script)" >&2; exit 1; }
done

KEYS="$HERE/../pathological/keys.txt"

# ── key material ────────────────────────────────────────────────────────────
mapfile -t KEYLINE < <(grep -v '^#' "$KEYS" | grep -v '^[[:space:]]*$')
xpub_of() { printf '%s\n' "${KEYLINE[$1]}" | sed 's/^\[[^]]*\]//'; }
fp_of()   { printf '%s\n' "${KEYLINE[$1]}" | sed 's/^\[\([0-9a-f]*\)\/.*/\1/'; }
path_of() { printf '%s\n' "${KEYLINE[$1]}" | sed 's/^\[[0-9a-f]*\/\([^]]*\)\].*/\1/'; }

mint() { # mint <xpub> <origin-path> <stub> [extra mk encode flags...]
  local xpub="$1" path="$2" stub="$3"; shift 3
  "$MK" encode --xpub "$xpub" --origin-path "$path" --policy-id-stub "$stub" \
        --group-size 0 "$@" 2>/dev/null
}

# A depth-5 child of pathological key <i>, at relative m/<c>.
#
# `mk derive` takes a CARD, so mint a throwaway one first. `mk encode` checks
# the xpub's depth and child number against the origin path's length and LAST
# component — and nothing else (measured 2026-08-30: "xpub origin-path
# mismatch: xpub depth 5 / child 7 vs origin_path depth 5 / last Normal{0}") —
# so every child at m/0 may declare the SAME 5-component path regardless of
# which parent it came from. That is what makes N distinct fp-free cards at
# ONE declared origin constructible from 11 keys.
child_of() { # child_of <parent 0..10> <child index>
  local i="$1" c="$2" tmp
  tmp=$(mint "$(xpub_of "$i")" "m/$(path_of "$i")" 00000000 \
              --origin-fingerprint "$(fp_of "$i")")
  # shellcheck disable=SC2086
  "$MK" derive --path "m/$c" $tmp 2>/dev/null | awk '/^child_xpub/{print $2}'
}

header() { # header <file> <row> <description>
  {
    echo "# $2 — $3"
    echo "# GENERATED by crates/md-cli/tests/fixtures/seating/generate.sh on $DATE."
    echo "# Key material: crates/md-cli/tests/fixtures/pathological/keys.txt (KEY n = its"
    echo "# n-th record, 1-based). md1 lines are the keyless policy card; mk1 lines are"
    echo "# the key cards. '#' and blank lines are provenance only."
  } > "$1"
}

# Shared 5-component paths for the fingerprint-free families. Depth-5 children
# at m/0 (component A) and m/1 (component B) — see child_of.
PA="48'/0'/0'/2'/0"
PB="48'/0'/1'/2'/1"

# ── V-COLLIDE ───────────────────────────────────────────────────────────────
f="$HERE/v-collide.txt"
header "$f" V-COLLIDE "two DIFFERENT cards pinned to one chunk-set id (0x12345)"
{
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35 --chunk-set-id 0x12345"
  echo "#   mk encode --xpub <KEY 2> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/1'/2' --policy-id-stub 5b48af35 --chunk-set-id 0x12345"
  echo "# Card A's chunks come FIRST so a test may take them alone and prove each card"
  echo "# decodes by itself — the refusal is the MERGED group, not a broken card."
  mint "$(xpub_of 0)" "m/$(path_of 0)" 5b48af35 --origin-fingerprint "$(fp_of 0)" --chunk-set-id 0x12345
  mint "$(xpub_of 1)" "m/$(path_of 1)" 5b48af35 --origin-fingerprint "$(fp_of 1)" --chunk-set-id 0x12345
} >> "$f"
echo "wrote: $f"

# ── V-IMPOSS ────────────────────────────────────────────────────────────────
# Two cards claiming the identical (fingerprint, path) with DIFFERENT xpubs.
# KEY 2's xpub is minted at KEY 1's origin: both are depth 4 and both paths end
# in 2', which is all `mk encode` checks, so the declaration is a lie the format
# itself cannot catch — exactly the case A2 has to.
f="$HERE/v-imposs.txt"
header "$f" V-IMPOSS "two cards, identical [73c5da0a/48'/0'/0'/2'], different xpubs"
{
  echo "#   md encode \"wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))\" \\"
  echo "#     --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a"
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  echo "#   mk encode --xpub <KEY 2> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35   <-- the lie"
  "$MD" encode "wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))" \
        --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint 73c5da0a
  mint "$(xpub_of 1)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint 73c5da0a
} >> "$f"
echo "wrote: $f"

# ── V-DOOR ──────────────────────────────────────────────────────────────────
# A policy whose @0 and @1 declare the IDENTICAL fingerprint-bearing origin.
# Its only possible fill binds one xpub to both slots.
f="$HERE/v-door.txt"
header "$f" V-DOOR "policy declaring two identical fingerprint-bearing slots"
{
  echo "#   md encode \"wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))\" \\"
  echo "#     --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a"
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  "$MD" encode "wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))" \
        --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint 73c5da0a
} >> "$f"
echo "wrote: $f"

# ── V-FPFREE-CARD ───────────────────────────────────────────────────────────
# @0 declares a fingerprint; the only card at @0's path is privacy-preserving,
# so it cannot meet that requirement blind and @0 is unfillable.
f="$HERE/v-fpfree-card.txt"
header "$f" V-FPFREE-CARD "fingerprint-free CARD against a fingerprint-BEARING declaration"
{
  echo "#   md encode \"wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))\" \\"
  echo "#     --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a"
  echo "#   mk encode --xpub <KEY 1> --privacy-preserving \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  echo "#   mk encode --xpub <KEY 2> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/1'/2' --policy-id-stub 5b48af35"
  "$MD" encode "wsh(multi(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/1'/2'/<0;1>/*))" \
        --fingerprint @0=73c5da0a --fingerprint @1=73c5da0a --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --privacy-preserving
  mint "$(xpub_of 1)" "m/48'/0'/1'/2'" 5b48af35 --origin-fingerprint 73c5da0a
} >> "$f"
echo "wrote: $f"

# ── V-R5M1 ──────────────────────────────────────────────────────────────────
# r5-M1's construction, REGROUNDED by the 2026-08-30 key-reuse ruling: @0 and
# @1 each appear in TWO group instances at the same use-site path, which is
# exactly the repetition BIP 388 forbids. It shipped as a measured
# over-strictness note; it is a REFUSE row now.
f="$HERE/v-r5m1.txt"
header "$f" V-R5M1 "two sortedmulti_a instances sharing placeholders at one path"
{
  echo "#   md encode \"tr(@2/48'/0'/0'/2'/<0;1>/*,{sortedmulti_a(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*),sortedmulti_a(1,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*)})\""
  echo "#   mk encode --xpub <KEY 1|5|9> --origin-fingerprint <its own> \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  "$MD" encode "tr(@2/48'/0'/0'/2'/<0;1>/*,{sortedmulti_a(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*),sortedmulti_a(1,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*)})" \
        --group-size 0 2>/dev/null
  for i in 0 4 8; do
    mint "$(xpub_of $i)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of $i)"
  done
} >> "$f"
echo "wrote: $f"

# ── V-BOUND-SEAT ────────────────────────────────────────────────────────────
# The SEAT side of the key-reuse boundary: fingerprint-free declarations at ONE
# path, two DIFFERENT masters. Pairwise-distinct keys, not reuse — and the
# sortedmulti group makes both assignments the same wallet, so it must SEAT.
f="$HERE/v-bound-seat.txt"
header "$f" V-BOUND-SEAT "fingerprint-free same-path declarations, two different masters"
{
  echo "#   md encode \"wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))\""
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  echo "#   mk encode --xpub <KEY 5> --origin-fingerprint b8688df1 \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  "$MD" encode "wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))" \
        --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of 0)"
  mint "$(xpub_of 4)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of 4)"
} >> "$f"
echo "wrote: $f"

# ── V-BOUND-REF ─────────────────────────────────────────────────────────────
# The REFUSE side, sitting adjacent so the boundary is pinned from BOTH
# directions: the SAME xpub offered as two cards (distinguished by their
# stubs, so they are two cards and not one duplicate the pipeline collapses).
f="$HERE/v-bound-ref.txt"
header "$f" V-BOUND-REF "the same xpub offered as two cards, for two slots"
{
  echo "#   md encode \"wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))\""
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 5b48af35"
  echo "#   mk encode --xpub <KEY 1> --origin-fingerprint 73c5da0a \\"
  echo "#     --origin-path m/48'/0'/0'/2' --policy-id-stub 00000000"
  "$MD" encode "wsh(sortedmulti(2,@0/48'/0'/0'/2'/<0;1>/*,@1/48'/0'/0'/2'/<0;1>/*))" \
        --group-size 0 2>/dev/null
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 5b48af35 --origin-fingerprint "$(fp_of 0)"
  mint "$(xpub_of 0)" "m/48'/0'/0'/2'" 00000000 --origin-fingerprint "$(fp_of 0)"
} >> "$f"
echo "wrote: $f"
