//! GENERATED by `cargo xtask verdicts` from
//! `crates/md-codec/tests/fixtures/coordinator/evidence.jsonl`. Do not edit.

#[allow(unused_imports)]
use super::{Cell, CellOutcome, Description, Form};

pub(super) static CELLS: &[Cell] = &[
];
