//! P0 SHAPE TESTS (`design/IMPLEMENTATION_PLAN_seat_auto_partition.md` P0
//! item 5) — assertions over the P0 fixtures, made entirely through the
//! SHIPPED `§1` canonical-key function
//! ([`super::canonical::canonical_piece_key`]), never a reimplementation
//! of its rule (plan-r1 M3). No seating behaviour is exercised here — P0
//! ships no partition engine; P1 wires one.
//!
//! Fixtures consumed (`crates/md-cli/tests/fixtures/seating/`, generated by
//! `generate.sh` + the sibling `mk` binary, except `v-ap2.txt` which is the
//! committed output of `src/bin/gen_ap2_grind.rs`):
//! `v-ap-shared.txt`, `v-ap-floor.txt`, `v-ap-boundary.txt`,
//! `v-ap-groupcap.txt`, `v-ap-incomplete.txt`, `v-ap2.txt`.

use super::canonical::canonical_piece_key;
use std::collections::{BTreeMap, HashSet};

fn mk1_lines(text: &str) -> Vec<&str> {
    text.lines()
        .map(str::trim)
        .filter(|l| l.starts_with("mk1"))
        .collect()
}

/// For each declared `chunk_index` present in `strings`, the number of
/// DISTINCT canonical pieces (SPEC §2.2's `count_i`) — computed entirely
/// via [`canonical_piece_key`], keyed by index so callers can assert shape
/// without assuming supply order.
fn per_index_distinct_counts(strings: &[&str]) -> BTreeMap<u8, usize> {
    let mut by_index: BTreeMap<u8, HashSet<_>> = BTreeMap::new();
    for s in strings {
        let key = canonical_piece_key(s).expect("fixture strings must be decodable mk1 pieces");
        by_index.entry(key.chunk_index).or_default().insert(key);
    }
    by_index
        .into_iter()
        .map(|(idx, set)| (idx, set.len()))
        .collect()
}

/// SPEC §2.4's product, `Σ_classes Π_indexes count_i`, over ONE class —
/// saturating (u64), matching the normative arithmetic rule (5^32
/// overflows u64; an unchecked `pow` panics under this repo's
/// `debug_assertions`-on test profile).
fn saturating_product(counts: &BTreeMap<u8, usize>) -> u64 {
    counts
        .values()
        .fold(1u64, |acc, &c| acc.saturating_mul(c as u64))
}

// ─── row 3 — shared-piece pair: chunk-0 identity ───────────────────────────

#[test]
fn shared_piece_pair_chunk_0_is_one_canonical_piece() {
    let strings = mk1_lines(include_str!("../../tests/fixtures/seating/v-ap-shared.txt"));
    assert_eq!(strings.len(), 6, "2 cards x 3 chunks");
    let by_index = per_index_distinct_counts(&strings);
    assert_eq!(by_index.len(), 3, "3 declared indices");
    // Index 0: the two cards' chunk-0 strings must canonicalise to the
    // SAME piece (the 13-shared-stub construction) -- distinct count 1.
    assert_eq!(
        by_index[&0], 1,
        "chunk 0 must be ONE canonical piece, shared by both cards"
    );
    // Indexes 1 and 2 carry each card's own fp/xpub content -- distinct.
    assert_eq!(
        by_index[&1], 2,
        "chunk 1 must be two DISTINCT pieces (differing fp/xpub)"
    );
    assert_eq!(
        by_index[&2], 2,
        "chunk 2 must be two DISTINCT pieces (differing fp/xpub)"
    );

    // Direct identity check, independent of the counting helper above:
    // the two chunk-0 strings' keys must compare EQUAL under `PartialEq`.
    let chunk0_keys: Vec<_> = strings
        .iter()
        .map(|s| canonical_piece_key(s).unwrap())
        .filter(|k| k.chunk_index == 0)
        .collect();
    assert_eq!(chunk0_keys.len(), 2, "both cards supply a chunk-0 string");
    assert_eq!(
        chunk0_keys[0], chunk0_keys[1],
        "the two chunk-0 pieces must be canonically IDENTICAL"
    );
}

// ─── row 4 — floor (n=11) / boundary (n=12): per-index counts + products ──

#[test]
fn floor_set_has_three_distinct_pieces_at_every_index_product_3_pow_11() {
    let strings = mk1_lines(include_str!("../../tests/fixtures/seating/v-ap-floor.txt"));
    assert_eq!(strings.len(), 33, "3 cards x 11 chunks");
    let by_index = per_index_distinct_counts(&strings);
    assert_eq!(by_index.len(), 11, "11 declared indices");
    for (idx, count) in &by_index {
        assert_eq!(
            *count, 3,
            "index {idx}: distinct stub lists must give 3 distinct pieces, not fewer"
        );
    }
    let product = saturating_product(&by_index);
    assert_eq!(
        product,
        3u64.pow(11),
        "3^11 = 177,147 (AP3's guaranteed floor)"
    );
    assert_eq!(product, 177_147);
}

#[test]
fn boundary_set_has_three_distinct_pieces_at_every_index_product_3_pow_12() {
    let strings = mk1_lines(include_str!(
        "../../tests/fixtures/seating/v-ap-boundary.txt"
    ));
    assert_eq!(strings.len(), 36, "3 cards x 12 chunks");
    let by_index = per_index_distinct_counts(&strings);
    assert_eq!(by_index.len(), 12, "12 declared indices");
    for (idx, count) in &by_index {
        assert_eq!(
            *count, 3,
            "index {idx}: distinct stub lists must give 3 distinct pieces, not fewer"
        );
    }
    let product = saturating_product(&by_index);
    assert_eq!(
        product,
        3u64.pow(12),
        "3^12 = 531,441 (the first refusing size)"
    );
    assert_eq!(product, 531_441);
    assert!(
        product > 3u64.pow(11),
        "the boundary product must exceed the floor product, or the two rows can't invert (r3-I1)"
    );
}

// ─── row 5 — over-budget synthetic (n=32): via the chunker ─────────────────

#[test]
fn over_budget_synthetic_set_has_five_distinct_pieces_at_every_index_product_saturates() {
    // 5 synthetic cards declaring total_chunks = 32 -- the size no real
    // `mk encode` invocation can mint (r3 P-i: 21-chunk ceiling). Built at
    // test time via P0's synthetic chunker (item 1), never persisted as a
    // giant static fixture file.
    const CHUNK_SET_ID: u32 = 0x5_5555;
    const TOTAL_CHUNKS: u8 = 32;
    let owned: Vec<Vec<String>> = (0..5u8)
        .map(|card| super::synth::synth_card_strings(CHUNK_SET_ID, TOTAL_CHUNKS, card))
        .collect();
    let strings: Vec<&str> = owned.iter().flatten().map(String::as_str).collect();
    assert_eq!(strings.len(), 160, "5 cards x 32 chunks");

    let by_index = per_index_distinct_counts(&strings);
    assert_eq!(by_index.len(), 32, "32 declared indices");
    for (idx, count) in &by_index {
        assert_eq!(
            *count, 5,
            "index {idx}: 5 synthetic cards must give 5 distinct pieces, not fewer"
        );
    }

    let product = saturating_product(&by_index);
    // 5^32 ~= 2.3e22, far past u64::MAX (~1.8e19) -- saturating arithmetic
    // MUST clamp rather than wrap or panic (SPEC §2.4; this repo's test
    // profile keeps debug_assertions on, so an unchecked `pow`/`mul` would
    // panic here rather than silently wrapping).
    assert_eq!(
        product,
        u64::MAX,
        "5^32 must SATURATE to u64::MAX, not overflow-panic or wrap"
    );
    assert!(
        u128::from(5u64).pow(32) > u128::from(u64::MAX),
        "sanity: 5^32 truly exceeds u64::MAX"
    );
}

// ─── group-cap set: Sigma_classes k = 6 ─────────────────────────────────────

#[test]
fn group_cap_set_sums_k_across_both_classes_to_six() {
    let strings = mk1_lines(include_str!(
        "../../tests/fixtures/seating/v-ap-groupcap.txt"
    ));
    assert_eq!(strings.len(), 15, "3 cards x 2 chunks + 3 cards x 3 chunks");

    // Sub-group by DECLARED total_chunks (SPEC §2.1) -- the two-class split
    // -- entirely via canonical_piece_key, then take k_class = the class's
    // per-index distinct count (uniform within a class here, since every
    // card in a class supplies exactly one distinct piece per index).
    let mut by_class: BTreeMap<u8, Vec<_>> = BTreeMap::new();
    for s in &strings {
        let key = canonical_piece_key(s).unwrap();
        by_class.entry(key.total_chunks).or_default().push(key);
    }
    assert_eq!(
        by_class.len(),
        2,
        "must be exactly two total-chunks classes"
    );

    let mut sigma_k = 0usize;
    for (total_chunks, keys) in &by_class {
        let mut by_index: BTreeMap<u8, HashSet<_>> = BTreeMap::new();
        for k in keys {
            by_index.entry(k.chunk_index).or_default().insert(k.clone());
        }
        assert_eq!(
            by_index.len(),
            *total_chunks as usize,
            "class {total_chunks}: every index must be present"
        );
        let k_class = by_index
            .values()
            .map(HashSet::len)
            .max()
            .expect("non-empty class");
        for (idx, set) in &by_index {
            assert_eq!(
                set.len(),
                k_class,
                "class {total_chunks}, index {idx}: per-index distinct count must equal k_class (3 real, distinguishable cards)"
            );
        }
        assert_eq!(k_class, 3, "each class holds exactly 3 distinct cards");
        sigma_k += k_class;
    }
    assert_eq!(
        sigma_k, 6,
        "Sigma_classes k must be 6 -- the group-wide AP3 cap (r3-I5) operates on THIS sum"
    );
}

// ─── incomplete-class set: the 3-chunk class genuinely lacks an index ──────

#[test]
fn incomplete_class_set_3_chunk_class_is_missing_one_index() {
    let strings = mk1_lines(include_str!(
        "../../tests/fixtures/seating/v-ap-incomplete.txt"
    ));
    assert_eq!(
        strings.len(),
        4,
        "1 complete 2-chunk card + 2 of 3 chunks from the 3-chunk card"
    );

    let mut by_class: BTreeMap<u8, BTreeMap<u8, usize>> = BTreeMap::new();
    for s in &strings {
        let key = canonical_piece_key(s).unwrap();
        *by_class
            .entry(key.total_chunks)
            .or_default()
            .entry(key.chunk_index)
            .or_insert(0) += 1;
    }
    assert_eq!(
        by_class.len(),
        2,
        "must be exactly two total-chunks classes (2 and 3)"
    );

    // The 2-chunk class is COMPLETE: indices {0, 1} both present, once each.
    let two_chunk = by_class.get(&2).expect("a 2-chunk class must exist");
    assert_eq!(
        two_chunk.len(),
        2,
        "the 2-chunk class must have BOTH declared indices present"
    );
    assert_eq!(two_chunk.values().copied().collect::<Vec<_>>(), vec![1, 1]);

    // The 3-chunk class is INCOMPLETE: exactly {0, 1} present, index 2 is
    // GENUINELY absent -- not merely under-counted (r1-C3's separating shape).
    let three_chunk = by_class.get(&3).expect("a 3-chunk class must exist");
    assert_eq!(
        three_chunk.len(),
        2,
        "the 3-chunk class must be missing exactly one of its 3 indices"
    );
    let present: std::collections::BTreeSet<u8> = three_chunk.keys().copied().collect();
    assert_eq!(
        present,
        [0u8, 1u8].into_iter().collect(),
        "indices 0 and 1 present"
    );
    assert!(
        !present.contains(&2),
        "index 2 must be genuinely absent, not merely double-counted elsewhere"
    );
}

// ─── row 9 — AP2 fixture: the hidden extra candidate verifies ─────────────

#[test]
fn ap2_fixture_hidden_extra_candidate_verifies_under_mk_codec_decode() {
    let strings = mk1_lines(include_str!("../../tests/fixtures/seating/v-ap2.txt"));
    assert_eq!(
        strings.len(),
        9,
        "cards A, B and C, 3 chunks each (r3-I4's [2,3,3] construction)"
    );

    // Fixed layout the generator writes: A's 3 chunks, then B's, then C's,
    // each in chunk_index order (0,1,2) -- asserted from the parsed
    // headers below rather than merely trusted from position.
    let keys: Vec<_> = strings
        .iter()
        .map(|s| canonical_piece_key(s).unwrap())
        .collect();
    for (i, k) in keys.iter().enumerate() {
        assert_eq!(k.total_chunks, 3);
        assert_eq!(
            k.chunk_index,
            (i % 3) as u8,
            "chunk_index must cycle 0,1,2 per card in file order"
        );
    }
    // A and B (the first two cards) must share chunk 0 (r3-I4's construction).
    assert_eq!(
        keys[0], keys[3],
        "card A's chunk 0 and card B's chunk 0 must be the SAME canonical piece"
    );
    // C's chunk 0 (the third card) must be a DIFFERENT piece.
    assert_ne!(
        keys[0], keys[6],
        "card C's chunk 0 must be a DIFFERENT canonical piece from A/B's"
    );

    // F = (C's chunk 0, A's chunk 1, A's chunk 2) -- never separately
    // supplied; reconstructed here purely from strings already in the
    // fixture (indices 6, 1, 2).
    let f = [strings[6], strings[1], strings[2]];
    let decoded = mk_codec::decode(&f);
    assert!(
        decoded.is_ok(),
        "F = (C0, A1, A2) must VERIFY under mk_codec::decode -- the fixture's whole point \
         (r3-I4): {decoded:?}"
    );

    // It must be a genuinely DIFFERENT card from A, B and C themselves --
    // otherwise this isn't an extra candidate at all.
    let card_a =
        mk_codec::decode(&[strings[0], strings[1], strings[2]]).expect("card A must decode alone");
    let card_b =
        mk_codec::decode(&[strings[3], strings[4], strings[5]]).expect("card B must decode alone");
    let card_c =
        mk_codec::decode(&[strings[6], strings[7], strings[8]]).expect("card C must decode alone");
    let card_f = decoded.unwrap();
    assert_ne!(card_f, card_a, "F must differ from A");
    assert_ne!(card_f, card_b, "F must differ from B");
    assert_ne!(card_f, card_c, "F must differ from C");
}
